databases:
  - name: trad-db
    plan: free
    databaseName: trad
    user: trad_user

services:
  - type: web
    name: trad-backend
    plan: free
    runtime: docker
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: trad-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*" # Set to your actual domain later
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - fromGroup: trad-secrets

envVarGroups:
  - name: trad-secrets
    envVars:
      - key: SUPABASE_ACCESS_KEY_ID
      - key: SUPABASE_SECRET_ACCESS_KEY
      - key: SUPABASE_STORAGE_BUCKET_NAME
      - key: SUPABASE_S3_REGION_NAME
      - key: FRONTEND_URL
