# Generated by Django 5.2.11 on 2026-03-09 23:16

import armodels.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('glb_file', models.FileField(upload_to=armodels.models.model_upload_path)),
                ('usdz_file', models.FileField(upload_to=armodels.models.model_upload_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=armodels.models.model_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
